BOARD ?= iotlab-m3
include ../Makefile.tests_common

FEATURES_REQUIRED += periph_flashpage
FEATURES_OPTIONAL += periph_flashpage_raw
FEATURES_OPTIONAL += periph_flashpage_page

USEMODULE += shell

include $(RIOTBASE)/Makefile.include
