ifneq (,$(filter stdio_uart,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart
endif
ifneq (,$(filter sx126x%,$(USEMODULE)))
  USEMODULE += sx126x_stm32wl
  USEMODULE += sx126x_rf_switch
endif
include $(RIOTBOARD)/common/nucleo/Makefile.dep
