ifneq (,$(filter netdev_default,$(USEMODULE)))
  ifeq (,$(filter socket_zep,$(USEMODULE)))
    USEMODULE += netdev_tap
  endif
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_native
endif

USEMODULE += native_drivers
